### ISSUE TITLE
broken code with current master commit

### ISSUE THREAD

**Issue by kampar** [sifsuska/bootleaf-faste#1]
nu, bisa kamu browse ke commit kamu yang lama?
laptop saya ke commit dan ke push auto merge .. sepertinya di rusaknya

yang ini masih jalan seharusnya, sebelum saya ... (punya kamu)
https://github.com/sifsuska/bootleaf-faste/tree/0b7c02ff58fb55754c9a6c02aa2a1019443e4097

kok tidak ada lagi fitur revert ya?

**Comment by ibnudana02** [comment]
done mr. jazman.
